# =============================================================================
# ‚òÑÔ∏è  vagari {{{
palette = "vagari"
version = "3"
# }}} ‚Æ≠
# =============================================================================

# ‚òØÔ∏è  Bounds{{{

bg = "#222536"
fg = "#aeb9f8"

[dark]
drk-0 = "#1e2133" # HSL: 231 26 16 CR: 1.05
drk-1 = "#181b2c" # HSL: 231 29 13 CR: 1.12
drk-2 = "#131626" # HSL: 231 33 11 CR: 1.18
drk-3 = "#0d0f1b" # HSL: 231 35 08 CR: 1.26

[black]
blk-0 = "#1d1d21" # HSL: 240 06 12 CR: 1.11
blk-1 = "#16161a" # HSL: 240 08 09 CR: 1.19
blk-2 = "#101014" # HSL: 240 11 07 CR: 1.25
blk-3 = "#0b0b0f" # HSL: 240 15 05 CR: 1.30

[bright]
brt-0 = "#b6c0f7" # HSL: 231 80 84 CR: 8.56
brt-1 = "#bec6f8" # HSL: 231 81 86 CR: 9.11
brt-2 = "#cad1fb" # HSL: 231 86 89 CR: 10.12
brt-3 = "#d1d8ff" # HSL: 231 100 91 CR: 11.21

[white]
wht-0 = "#c9c9e2" # HSL: 240 30 84 CR: 9.33
wht-1 = "#d3d3ed" # HSL: 240 42 88 CR: 10.41
wht-2 = "#ddddf6" # HSL: 240 58 92 CR: 11.36
wht-3 = "#e9e9fb" # HSL: 240 69 95 CR: 12.63

# }}} ‚Æ≠

# üö• Signaling {{

[red]
red-0 = "#f34658" # HSL: 354 88 61 CR: 4.20
red-2 = "#ef5d6e" # HSL: 353 82 65 CR: 4.66
red-1 = "#f06b7d" # HSL: 342 82 68 CR: 5.12
red-3 = "#f07a88" # HSL: 353 80 71 CR: 5.66
red-4 = "#f68e99" # HSL: 354 88 76 CR: 6.67

[orange]
orn-0 = "#e56b2c" # HSL: 20 78 54 CR: 4.66
orn-1 = "#ea834b" # HSL: 21 79 61 CR: 5.66
orn-2 = "#eb905d" # HSL: 22 78 64 CR: 6.26
orn-3 = "#f2a170" # HSL: 23 83 70 CR: 7.29
orn-4 = "#f8b486" # HSL: 24 89 75 CR: 8.56

[yellow]
yel-0 = "#f3a338" # HSL: 34 89 59 CR: 7.29
yel-1 = "#f5b855" # HSL: 37 89 65 CR: 8.56
yel-2 = "#f5c069" # HSL: 37 87 69 CR: 9.11
yel-3 = "#f4ce88" # HSL: 39 83 75 CR: 10.12
yel-4 = "#f5d599" # HSL: 39 82 78 CR: 10.72

[ivy]
ivy-0 = "#2d9a47" # HSL: 134 55 39 CR: 4.20
ivy-1 = "#48a95b" # HSL: 132 40 47 CR: 5.12
ivy-2 = "#5aba6d" # HSL: 132 41 54 CR: 6.26
ivy-3 = "#5fc976" # HSL: 133 50 58 CR: 7.29
ivy-4 = "#76d78b" # HSL: 133 55 65 CR: 8.56

[cyan]
cyn-0 = "#a8fff9" # HSL: CR:
cyn-1 = "#4adecd" # HSL: CR:
cyn-2 = "#4adecd" # HSL: CR:
cyn-3 = "#4adecd" # HSL: CR:
cyn-4 = "#02bba5" # HSL: CR:

[pink]
pnk-0 = "#ff94d4" # HSL: CR:
pnk-1 = "#dc60bf" # HSL: CR:
pnk-2 = "#dc60bf" # HSL: CR:
pnk-3 = "#dc60bf" # HSL: CR:
pnk-4 = "#b7349f" # HSL: CR:

# }}} ‚Æ≠

# üì° Communicative{{{

[green]
grn-0 = "#b7e6a3" # HSL: CR:
grn-1 = "#86b96f" # HSL: CR:
grn-2 = "#86b96f" # HSL: CR:
grn-3 = "#86b96f" # HSL: CR:
grn-4 = "#86b96f" # HSL: CR:
grn-5 = "#5e9249" # HSL: CR:

[azure]
azr-0 = "#9edbff" # HSL: CR:
azr-1 = "#59b5e5" # HSL: CR:
azr-2 = "#59b5e5" # HSL: CR:
azr-3 = "#59b5e5" # HSL: CR:
azr-4 = "#59b5e5" # HSL: CR:
azr-5 = "#2a87c7" # HSL: CR:

[blue]
blu-0 = "#a2b4fa" # HSL: CR:
blu-1 = "#6c88f4" # HSL: CR:
blu-2 = "#6c88f4" # HSL: CR:
blu-3 = "#6c88f4" # HSL: CR:
blu-4 = "#6c88f4" # HSL: CR:
blu-5 = "#3d60e6" # HSL: CR:

[purple]
prp-0 = "#c2aafc" # HSL: CR:
prp-1 = "#9d7af0" # HSL: CR:
prp-2 = "#9d7af0" # HSL: CR:
prp-3 = "#9d7af0" # HSL: CR:
prp-4 = "#9d7af0" # HSL: CR:
prp-5 = "#8f40e3" # HSL: CR:

# }}} ‚Æ≠

# ‚öóÔ∏è  Muted{{{

[histidine]
his-0 = "#cf9590" # HSL: CR:
his-1 = "#cf9590" # HSL: CR:

[glutamic]
glu-0 = "#8ba5cb" # HSL: CR:
glu-1 = "#8ba5cb" # HSL: CR:

[aparagine]
asn-0 = "#c293cd" # HSL: CR:
asn-1 = "#c293cd" # HSL: CR:

[proline]
pro-0 = "#c2cf90" # HSL: CR:
pro-1 = "#c2cf90" # HSL: CR:

[tyrosine]
tyr-0 = "#9dd4c2" # HSL: CR:
tyr-1 = "#9dd4c2" # HSL: CR:

# }}} ‚Æ≠

# üëΩ greys{{{

[rust]
rst-0 = "#8f6557" # HSL: CR:
rst-1 = "#7e5a4e" # HSL: CR:
rst-2 = "#755448" # HSL: CR:
rst-3 = "#6c4d42" # HSL: CR:
rst-4 = "#62463c" # HSL: CR:
rst-5 = "#553c34" # HSL: CR:

[slate]
slt-0 = "#646ca0" # HSL: CR:
slt-1 = "#596091" # HSL: CR:
slt-2 = "#515885" # HSL: CR:
slt-3 = "#4c527b" # HSL: CR:
slt-4 = "#444a6f" # HSL: CR:
slt-5 = "#3c4162" # HSL: CR:

[plum]
plm-0 = "#816681" # HSL: CR:
plm-1 = "#725a72" # HSL: CR:
plm-2 = "#6a536a" # HSL: CR:
plm-3 = "#614c61" # HSL: CR:
plm-4 = "#594659" # HSL: CR:
plm-5 = "#4d3d4d" # HSL: CR:

[olive]
olv-0 = "#6a716a" # HSL: CR:
olv-1 = "#5e645e" # HSL: CR:
olv-2 = "#565c56" # HSL: CR:
olv-3 = "#4f544f" # HSL: CR:
olv-4 = "#484c48" # HSL: CR:
olv-5 = "#3e423e" # HSL: CR:

[grey]
gry-0 = "#696d86" # HSL: CR:
gry-1 = "#5e6178" # HSL: CR:
gry-2 = "#585b6f" # HSL: CR:
gry-3 = "#515467" # HSL: CR:
gry-4 = "#484b5b" # HSL: CR:
gry-5 = "#3f4150" # HSL: CR:

# }}} ‚Æ≠

# =============================================================================
# üí° References {{

# unity:
# 12::0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330
#  5::0, 72, 144, 216, 288

# constants:
# ‚àö2: 1.414
# e: 2.718
#   - inv(e): 0.367
# Œ¶: 1.618
# œÄ: 3.141
# Œ¥: 4.669
# ‚Ñè: 6.626
# …ë: 7.297
# m_e: 9.109

# prime:
# 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97

# perfect:
# 6, 28, 496, 8 128

[eww_v1]
red-d = "#e0617a"     # CR: 4.44 | RL: 25.8
red = "#f7768e"       # CR: 5.72 | RL: 34.7
red-l = "#ff8ba2"     # CR: 6.83 | RL: 42.3
orange-d = "#e4874e"  # CR: 5.68 | RL: 34.4
orange = "#ff9e64"    # CR: 7.45 | RL: 46.6
orange-l = "#ffb67a"  # CR: 8.82 | RL: 56.1
yellow-d = "#c79852"  # CR: 5.80 | RL: 35.2
yellow = "#f5ce73"    # CR: 10.07| RL: 64.8
yellow-l = "#fac77e"  # CR: 9.76 | RL: 62.7
green-d = "#85b553"   # CR: 6.30 | RL: 38.7
green = "#9ece6a"     # CR: 8.29 | RL: 52.4
green-l = "#b7e882"   # CR: 10.73| RL: 69.4
cyan-d = "#58c0b0"    # CR: 6.91 | RL: 42.9
cyan = "#73daca"      # CR: 9.09 | RL: 58.0
cyan-l = "#8ef5e4"    # CR: 11.78| RL: 76.7
azure-d = "#6cb1dc"   # CR: 6.46 | RL: 39.8
azure = "#86caf6"     # CR: 8.50 | RL: 54.0
azure-l = "#a0e4ff"   # CR: 10.84| RL: 70.2
blue-d = "#5784d5"    # CR: 4.08 | RL: 23.3
blue = "#7aa2f7"      # CR: 6.01 | RL: 36.7
blue-l = "#91b7ff"    # CR: 7.51 | RL: 47.1
purple-d = "#997ad4"  # CR: 4.39 | RL: 25.4
purple = "#bb9af7"    # CR: 6.55 | RL: 40.4
purple-l = "#d2b0ff"  # CR: 8.22 | RL: 52.0
pink-d = "#df7fbe"    # CR: 5.n1 | RL: 34.6
pink = "#f896d6"      # CR: 7.44 | RL: 46.6
pink-l = "#ffaeee"    # CR: 9.04 | RL: 57.7
red-gd = "#4d2a30"    # CR: 1.21 | RL: 03.4
red-g = "#753c45"     # CR: 1.79 | RL: 07.4
red-gl = "#d0a4a9"    # CR: 6.90 | RL: 42.8
blue-gd = "#2c354c"   # CR: 1.24 | RL: 03.6
blue-g = "#3f4e74"    # CR: 1.84 | RL: 07.8
blue-gl = "#9fadd8"   # CR: 6.81 | RL: 42.2
sakura = "#ffb7c5"    # CR: 9.25 | RL: 59.2
beige = "#cfc9c2"     # CR: 9.22 | RL: 58.9
celeste = "#b4f9f8"   # CR: 12.87| RL: 84.2
turquoise = "#2ac3de" # CR: 7.18 | RL: 44.8
royal = "#4169e1"     # CR: 3.12 | RL: 16.7
navy = "#222d56"      # CR: 1.13 | RL: 03.0

[cava]
blue = "#90a6d1"       # CR: 6.17 | RL: 37.8
azure = "#91bcd1"      # CR: 7.44 | RL: 46.6
cyan = "#95c4b4"       # CR: 7.81 | RL: 49.2
green = "#c0ca8e"      # CR: 8.71 | RL: 55.4
yellow = "#ded199"     # CR: 9.87 | RL: 63.4
orange = "#e9b189"     # CR: 8.01 | RL: 50.6
red = "#e98989"        # CR: 6.06 | RL: 37.0
pink = "#d982ab"       # CR: 5.57 | RL: 33.7
background = "#222536" # CR: 1.00 RL: 1.93

[toyonight]
red = "#f7768e"        # CR: 5.50 | RL: 34.7
orange = "#ff9e64"     # CR: 7.16 | RL: 46.6
yellow = "#e0af68"     # CR: 7.28 | RL: 47.5
green = "#9ece6a"      # CR: 7.97 | RL: 52.4
cyan = "#73daca"       # CR: 8.74 | RL: 58.1
regex = "#b4f9f8"      # CR: 12.37| RL: 84.2
element = "#2ac3de"    # CR: 6.90 | RL: 44.8
cyan2 = "#7dcfff"      # CR: 8.49 | RL: 56.2
blue = "#7aa2f7"       # CR: 5.78 | RL: 36.7
magenta = "#bb9af7"    # CR: 6.29 | RL: 40.3
whtie = "#c0caf5"      # CR: 9.02 | RL: 60.0
fg = "#a9b1d6"         # CR: 6.89 | RL: 44.7
text = "#9aa5ce"       # CR: 5.99 | RL: 38.2
parameter = "#cfc9c2"  # CR: 8.86 | RL: 59.0
comment = "#565f89"    # CR: 2.35 | RL: 12.0
black = "#414868"      # CR: 1.63 | RL: 06.8
background = "#24283b" # CR: 1.00 | RL: 02.2

[iceberg]
background = "#1d1f21" # CR: 1.00 | RL: 01.4
foreground = "#c5c8c6" # CR: 9.80 | RL: 57.3

[iceberg.normal]
black = "#282a2e"   # CR: 1.15 | RL: 02.3
red = "#a54242"     # CR: 2.72 | RL: 12.3
green = "#8c9440"   # CR: 5.05 | RL: 27.1
yellow = "#de935f"  # CR: 6.64 | RL: 37.2
blue = "#5f819d"    # CR: 4.02 | RL: 20.6
magenta = "#85678f" # CR: 3.41 | RL: 16.7
cyan = "#5e8d87"    # CR: 4.43 | RL: 23.2
white = "#707880"   # CR: 3.69 | RL: 18.4

[iceberg.bright]
black = "#373b41"   # CR: 1.46 | RL: 04.3
red = "#cc6666"     # CR: 4.45 | RL: 23.3
green = "#b5bd68"   # CR: 8.22 | RL: 47.2
yellow = "#f0c674"  # CR: 10.26| RL: 60.2
blue = "#81a2be"    # CR: 6.17 | RL: 34.2
magenta = "#b294bb" # CR: 6.17 | RL: 34.2
cyan = "#8abeb7"    # CR: 7.97 | RL: 45.6
white = "#c5c8c6"   # CR: 9.80 | RL: 57.3


[catpuccin-macchiatoo]
Rosewater = "#f4dbd6" #  CR: 11.18| RL: 74.8
Flamingo = "#f0c6c6"  #  CR: 9.53 | RL: 63.0
Pink = "#f5bde6"      #  CR: 9.32 | RL: 61.5
Mauve = "#c6a0f6"     #  CR: 6.84 | RL: 43.8
Red = "#ed8796"       #  CR: 5.96 | RL: 37.5
Maroon = "#ee99a0"    #  CR: 6.80 | RL: 43.5
Peach = "#f5a97f"     #  CR: 7.61 | RL: 49.3
Yellow = "#eed49f"    #  CR: 10.2 | RL: 67.8
Green = "#a6da95"     #  CR: 9.17 | RL: 60.4
Teal = "#8bd5ca"      #  CR: 8.74 | RL: 57.3
Sky = "#91d7e3"       #  CR: 9.13 | RL: 60.2
Sapphire = "#7dc4e4"  #  CR: 7.63 | RL: 49.4
Blue = "#8aadf4"      #  CR: 6.56 | RL: 41.8
Lavender = "#b7bdf8"  #  CR: 8.16 | RL: 53.2
Text = "#cad3f5"      #  CR: 9.91 | RL: 65.7
Subtext1 = "#b8c0e0"  #  CR: 8.17 | RL: 53.3
Subtext0 = "#a5adcb"  #  CR: 6.61 | RL: 42.2
Overlay2 = "#939ab7"  #  CR: 5.29 | RL: 32.7
Overlay1 = "#8087a2"  #  CR: 4.14 | RL: 24.5
Overlay0 = "#6e738d"  #  CR: 3.15 | RL: 17.5
Surface2 = "#5b6078"  #  CR: 2.37 | RL: 11.9
Surface1 = "#494d64"  #  CR: 1.77 | RL: 07.6
Surface0 = "#363a4f"  #  CR: 1.31 | RL: 04.4
Base = "#24273a"      #  CR: 1.00 | RL: 02.1
Mantle = "#1e2030"    #  CR: 1.09 | RL: 01.5
Crust = "#181926"     #  CR: 1.18 | RL: 01.0

# }}} ‚Æ≠
# =============================================================================
